name: Build static ffmpeg

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      ARCH: x86_64
      FFMPEG_VERSION: 7.0.2
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y \
            yasm \
            build-essential \
            wget

      - name: install opus 1.5.2
        run: |
          wget https://downloads.xiph.org/releases/opus/opus-1.5.2.tar.gz
          tar -xzvf opus-1.5.2.tar.gz
          cd opus-1.5.2

          ./configure
          make
          sudo make install

          sudo ldconfig

      - name: Install ARM64 compiler
        if: env.ARCH == 'arm64'
        run: |
          sudo apt-get update -y && \
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build
        run: ./build-linux.sh

      - name: Make tarballs
        run: |
          mkdir -p artifacts/release/
          find . -name 'ffmpeg' -type f -exec sh -c 'tar -czvf artifacts/release/ffmpeg-${{ env.arch }}.tar.gz -C $(dirname {}) $(basename {})' \;
          ls -l artifacts/release/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: artifacts/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
